cursor #e2e1ef
cursor_text_color #c3c5dd

foreground            #e2e1ef
background            #11131c
selection_foreground  #003546
selection_background  #8ad0ef
url_color             #64d3ff

color0   #11131c
color1   #ff548c
color2   #63ff75
color3   #fff454
color4   #41c0f2
color5   #005476
color6   #64d3ff
color7   #ecf9ff
color8   #96a1a5
color9   #ff8ab0
color10  #92ff9e
color11  #fff892
color12  #7bd9ff
color13  #92e0ff
color14  #b9ebff
color15  #f7fcff
